version: '3.8'

services:
  warehouse-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: smartchaincontrol
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - VIRTUAL_HOST=smartchaincontrol.szenassy-akos.com
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    external: true